### ISSUE TITLE
hex package

### ISSUE THREAD

**Issue by Licenser** [goj/base16#4]
It would be really great if a hex package could be provided. I can gladly make a PR with all needed changes to do it nicely.

**Comment by goj** [comment]
I'm waiting for a PR then :)

**Comment by Licenser** [comment]
submitted :)

**Comment by goj** [comment]
Thanks a lot!

Sorry for taking so long to review it but I have zero free time lately. I'll try to take a look at the PR this weekend.

**Comment by Licenser** [comment]
No worries, I totally understand how that goes ;)

**Comment by Licenser** [comment]
Sorry to ping you again any chance to publish the package to hex too?

It's really easy with rebar3: http://www.rebar3.org/docs/publishing-packages

**Comment by goj** [comment]
Last time I tried to publish it, rebar3's hex plugin crashed with stack
trace pointing at some error-printing code. I'll try later on this week,
maybe a new, less broken version was published in the meantime.

**Comment by Licenser** [comment]
if things crash again, a ticket to rebar3 repo would probably be great, they respond really quickly and it'd improve rebar3 for everyone :)
